### ISSUE TITLE
Cut-off outputs, unreliable

### ISSUE THREAD

**Issue by Kav-K** [ferrislucas/promptr#15]
Hey!

Great project, but I've found that a lot of times, the output is cut off by the model:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/21161101/230826106-edf10e5e-e1ec-4b00-8509-05bc1dcbc8d6.png">

Moreover, using GPT-4 fails, it just doesn't return sometimes

**Comment by ferrislucas** [comment]
Hi @Kav-K - thanks for reaching out! Gpt3 is pretty limited because of the smaller context window. Not much will fit - I’ve been using gpt4 with pretty good results though. 

Are you’re able to share the command you used? 

Also, any chance this is a public code base so I can try the command you used against the same code?

**Comment by ferrislucas** [comment]
Happy to re-open this if you have any more info @Kav-K
