### ISSUE TITLE
Error when any prompt ran

### ISSUE THREAD

**Issue by john-h-k** [ferrislucas/promptr#30]
Whenever I run `promptr` I get an error along the lines of

```
Execution time: 7194ms
undefined:1
--BEGIN-FILE: test.rb
 ^

SyntaxError: No number after minus sign in JSON at position 1
```

**Comment by mossy426** [comment]
I've got this as well

**Comment by ferrislucas** [comment]
This happens when the model returns invalid json. I’ve seen this a lot with gpt3 but not with gpt4. 

If you use the -v option then you can see what the model responds with before promptr attempts to parse the response as json. You’ll probably see that the response has some content before the json begins. 

I’m going to spend some time experimenting with how to compensate for this. GPT3 just really likes to preface its json response with various not-json things.

**Comment by ferrislucas** [comment]
@mossy426 please make sure you have the most recent version. It’s a bit better, but there is still more work to be done.

**Comment by ews** [comment]
@ferrislucas I am having exactly the same problem with the last version (and gpt3, I am not on gpt4 yet)

**Comment by ferrislucas** [comment]
https://github.com/ferrislucas/promptr/pull/35 should help this a lot. 
Please update to 3.0.6. 
GPT3 will still sometimes output cutoff or invalid json which causes issues.
